import { BACKEND_URL } from "./env";

export const API_ENDPOINTS = {
  LOGIN: `${BACKEND_URL}/auth/login`,
  REGISTER: `${BACKEND_URL}/auth/register`,
  FORGETPASSWORD: `${BACKEND_URL}/auth/forgot_password`,
  RESETPASSWORD: `${BACKEND_URL}/auth/reset-password`,
  VERIFY_PASSWORD: `${BACKEND_URL}/auth/verify-password`,
  MY_PROFILE: `${BACKEND_URL}/auth/me`,
  GET_ALL_ITEMS: `${BACKEND_URL}/items`,
  CREATE_ITEM: `${BACKEND_URL}/items`,
  GET_ITEM_DETAIL: (id: string) => `${BACKEND_URL}/items/${id}`,
  UPDATE_ITEM: (id: string) => `${BACKEND_URL}/items/${id}`,
  DELETE_ITEM: (id: string) => `${BACKEND_URL}/items/${id}`,
  GET_POSTER: `${BACKEND_URL}/poster`,
  UPLOAD_POSTER: `${BACKEND_URL}/poster`,
  DELETE_POSTER: `${BACKEND_URL}/poster`,
  GET_HERO_SLIDES: `${BACKEND_URL}/hero-slides`,
  CREATE_HERO_SLIDE: `${BACKEND_URL}/hero-slides`,
  UPDATE_HERO_SLIDE: (id: string) => `${BACKEND_URL}/hero-slides/${id}`,
  DELETE_HERO_SLIDE: (id: string) => `${BACKEND_URL}/hero-slides/${id}`,
  GET_BEST_SELLERS: `${BACKEND_URL}/best-sellers`,
  CREATE_BEST_SELLER: `${BACKEND_URL}/best-sellers`,
  UPDATE_BEST_SELLER: (id: string) => `${BACKEND_URL}/best-sellers/${id}`,
  DELETE_BEST_SELLER: (id: string) => `${BACKEND_URL}/best-sellers/${id}`,
  CREATE_ORDER: `${BACKEND_URL}/orders`,
  GET_ALL_ORDERS: `${BACKEND_URL}/orders`,
  GET_MY_ORDERS: `${BACKEND_URL}/orders/my`,
  GET_ORDER_DETAIL: (id: string) => `${BACKEND_URL}/orders/${id}`,
  UPDATE_ORDER: (id: string) => `${BACKEND_URL}/orders/${id}`,
  DELETE_ORDER: (id: string) => `${BACKEND_URL}/orders/${id}`,
  GET_REVIEWS: (itemId: string) => `${BACKEND_URL}/reviews?itemId=${itemId}`,
  GET_ALL_REVIEWS: `${BACKEND_URL}/reviews/all`,
  CREATE_REVIEW: `${BACKEND_URL}/reviews`,
  DELETE_REVIEW: (id: string) => `${BACKEND_URL}/reviews/${id}`,
  VALIDATE_PROMO: `${BACKEND_URL}/promo-codes/validate`,
  GET_PROMO_CODES: `${BACKEND_URL}/promo-codes`,
  CREATE_PROMO_CODE: `${BACKEND_URL}/promo-codes`,
  UPDATE_PROMO_CODE: (id: string) => `${BACKEND_URL}/promo-codes/${id}`,
  DELETE_PROMO_CODE: (id: string) => `${BACKEND_URL}/promo-codes/${id}`,
} as const;
